package moze_intel.projecte.common;

import moze_intel.projecte.PECore;
import moze_intel.projecte.api.data.CustomConversionProvider;
import moze_intel.projecte.api.nss.NSSFake;
import moze_intel.projecte.api.nss.NSSItem;
import moze_intel.projecte.api.nss.NormalizedSimpleStack;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.FluidTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.*;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.alchemy.Potions;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.fluids.FluidType;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;

public class PECustomConversionProvider extends CustomConversionProvider {

	public PECustomConversionProvider(@NotNull PackOutput output, @NotNull CompletableFuture<HolderLookup.Provider> lookupProvider) {
		super(output, lookupProvider, PECore.MODID);
	}

	@Override
	protected void addCustomConversions(@NotNull HolderLookup.Provider registries) {
		createConversionBuilder(PECore.rl("metals"))
				.comment("Sets default conversions for various metals from other mods and their default values.")
				.before(Tags.Items.INGOTS_IRON, 16_384)
				.before(ingotTag("uranium"), 262_144)
				.before(Tags.Items.GEMS_AMETHYST, 2_048)
				.before(gemTag("ruby"), 131_072)
				.before(gemTag("sapphire"), 131_072)
				.before(gemTag("peridot"), 131_072)
				.conversion(Tags.Items.INGOTS_GOLD).ingredient(Tags.Items.INGOTS_IRON, 4).propagateTags().end()
				.conversion(Tags.Items.INGOTS_COPPER, 2).ingredient(Tags.Items.INGOTS_IRON).propagateTags().end()
				.conversion(ingotTag("tin")).ingredient(Tags.Items.INGOTS_IRON).propagateTags().end()
				.conversion(ingotTag("bronze"), 4).ingredient(ingotTag("copper"), 3).ingredient(ingotTag("tin")).propagateTags().end()
				.conversion(ingotTag("silver")).ingredient(Tags.Items.INGOTS_IRON, 2).propagateTags().end()
				.conversion(ingotTag("lead")).ingredient(Tags.Items.INGOTS_IRON, 2).propagateTags().end()
				.conversion(ingotTag("osmium")).ingredient(Tags.Items.INGOTS_IRON, 2).propagateTags().end()
				.conversion(ingotTag("nickel")).ingredient(Tags.Items.INGOTS_IRON, 2).propagateTags().end()
				.conversion(ingotTag("aluminum"), 2).ingredient(Tags.Items.INGOTS_IRON).propagateTags().end()
				.conversion(ingotTag("platinum")).ingredient(Tags.Items.INGOTS_IRON, 8).propagateTags().end()
				.conversion(ingotTag("cyanite"), 4).ingredient(ingotTag("uranium")).propagateTags().end()
		;
		NormalizedSimpleStack singleEMC = NSSFake.create("single_emc");
		ItemStack waterBottle = PotionContents.createItemStack(Items.POTION, Potions.WATER);
		createConversionBuilder(PECore.rl("defaults"))
				.comment("Default values for vanilla items.")
				.group("default")
				.comment("Default conversion group.")
				.conversion(Items.GRASS_BLOCK).ingredient(Items.DIRT, 2).end()
				.conversion(Items.PODZOL).ingredient(Items.DIRT, 2).end()
				.conversion(Items.ROOTED_DIRT).ingredient(Items.DIRT).ingredient(Items.HANGING_ROOTS).end()
				.conversion(Items.MYCELIUM).ingredient(Items.DIRT, 2).end()
				.conversion(Items.MUD).ingredient(Items.DIRT).ingredient(waterBottle).ingredient(Items.GLASS_BOTTLE, -1).end()
				.conversion(Items.CRIMSON_NYLIUM).ingredient(Items.NETHERRACK, 2).end()
				.conversion(Items.WARPED_NYLIUM).ingredient(Items.NETHERRACK, 2).end()
				.conversion(Items.IRON_HORSE_ARMOR).ingredient(Tags.Items.INGOTS_IRON, 8).end()
				.conversion(Items.GOLDEN_HORSE_ARMOR).ingredient(Tags.Items.INGOTS_GOLD, 8).end()
				.conversion(Items.DIAMOND_HORSE_ARMOR).ingredient(Tags.Items.GEMS_DIAMOND, 8).end()
				.conversion(Items.CARVED_PUMPKIN).ingredient(Items.PUMPKIN).end()
				.conversion(Items.TORCHFLOWER_SEEDS).ingredient(Items.TORCHFLOWER).end()
				.conversion(Items.PITCHER_POD).ingredient(Items.PITCHER_PLANT).end()
				.conversion(Items.WRITTEN_BOOK).ingredient(Items.WRITABLE_BOOK).end()
				.conversion(Items.ENCHANTED_BOOK).ingredient(Items.BOOK).end()
				.conversion(Items.ENCHANTED_GOLDEN_APPLE).ingredient(Items.APPLE).ingredient(Tags.Items.STORAGE_BLOCKS_GOLD, 8).end()
				.conversion(Items.STRIPPED_BAMBOO_BLOCK).ingredient(Items.BAMBOO_BLOCK).end()
				.conversion(Items.GLOBE_BANNER_PATTERN).ingredient(Tags.Items.GEMS_EMERALD, 3).end()
				.conversion(Items.SKULL_BANNER_PATTERN, 3)
				.ingredient(Items.PAPER, 3)
				.ingredient(Items.NETHER_STAR)
				.ingredient(Items.SOUL_SAND, -256)
				.end()
				//Basic default firework/firework star calculations
				//Note: We don't use tags here as the recipes themselves don't use tags
				// A star with no color and default shape would line up to just being gunpowder
				.conversion(Items.FIREWORK_STAR).ingredient(Items.GUNPOWDER).end()
				// A rocket with no explosion and default flight duration would just be a piece of paper and gunpowder
				.conversion(Items.FIREWORK_ROCKET).ingredient(Items.PAPER).ingredient(Items.GUNPOWDER).end()
				//Note: suspicious blocks only can be gotten by them falling for over thirty seconds (for example bubble column)
				// and don't keep their loot if placed by a player, so we can just set them as the same as the normal block they
				// turn into after brushing
				.conversion(Items.SUSPICIOUS_GRAVEL).ingredient(Items.GRAVEL).end()
				.conversion(Items.SUSPICIOUS_SAND).ingredient(Items.SAND).end()
				.conversion(Items.WET_SPONGE).ingredient(Items.SPONGE).end()
				.conversion(Items.BELL).ingredient(Tags.Items.INGOTS_GOLD, 7).end()
				.conversion(Items.HONEYCOMB, 192).ingredient(Items.HONEY_BOTTLE).end()
				.conversion(Items.POWDER_SNOW_BUCKET).ingredient(Items.BUCKET).ingredient(Items.SNOW_BLOCK, 4).end()
				.conversion(Items.GLOW_INK_SAC).ingredient(Items.INK_SAC).ingredient(Tags.Items.DUSTS_GLOWSTONE).end()
				.conversion(Items.HANGING_ROOTS).ingredient(Tags.Items.RODS_WOODEN).end()
				.conversion(Items.SUSPICIOUS_STEW)
				.ingredient(Items.BOWL)
				.ingredient(Items.BROWN_MUSHROOM)
				.ingredient(Items.RED_MUSHROOM)
				.ingredient(ItemTags.SMALL_FLOWERS)
				.end()
				.conversion(Items.PUFFERFISH_BUCKET).ingredient(Items.WATER_BUCKET).ingredient(Items.PUFFERFISH).end()
				.conversion(Items.SALMON_BUCKET).ingredient(Items.WATER_BUCKET).ingredient(Items.SALMON).end()
				.conversion(Items.COD_BUCKET).ingredient(Items.WATER_BUCKET).ingredient(Items.COD).end()
				.conversion(Items.TROPICAL_FISH_BUCKET).ingredient(Items.WATER_BUCKET).ingredient(Items.TROPICAL_FISH).end()
				.conversion(Items.DRAGON_BREATH).ingredient(Items.GLASS_BOTTLE).ingredient(singleEMC).end()
				.conversion(Items.SOUL_SOIL).ingredient(Items.SOUL_SAND).end()
				.conversion(Items.WARPED_WART_BLOCK).ingredient(Items.NETHER_WART_BLOCK).end()
				.conversion(Items.SHROOMLIGHT).ingredient(Items.GLOWSTONE_DUST).ingredient(Tags.Items.MUSHROOMS).end()
				.conversion(Items.OCHRE_FROGLIGHT, 192).ingredient(Items.MAGMA_CREAM).end()
				.conversion(Items.PEARLESCENT_FROGLIGHT, 192).ingredient(Items.MAGMA_CREAM).end()
				.conversion(Items.VERDANT_FROGLIGHT, 192).ingredient(Items.MAGMA_CREAM).end()
				.conversion(Items.SCULK).ingredient(Items.SCULK_VEIN, 4).end()
				.conversion(Items.SCULK_SENSOR).ingredient(Items.COMPARATOR, 4).ingredient(Items.REPEATER, 4).ingredient(Items.SCULK, 1).end()
				.conversion(Items.SCULK_SHRIEKER).ingredient(Items.SCULK_CATALYST, 4).end()
				.end()
				.group("dirt_path")
				.comment("Adds the various valid conversions into dirt paths.")
				//Dirt paths can be made from a variety of blocks
				.conversion(Items.DIRT_PATH).ingredient(Items.GRASS_BLOCK).end()
				.conversion(Items.DIRT_PATH).ingredient(Items.DIRT).end()
				.conversion(Items.DIRT_PATH).ingredient(Items.PODZOL).end()
				.conversion(Items.DIRT_PATH).ingredient(Items.COARSE_DIRT).end()
				.conversion(Items.DIRT_PATH).ingredient(Items.MYCELIUM).end()
				.conversion(Items.DIRT_PATH).ingredient(Items.ROOTED_DIRT).end()
				.end()
				.group("chainmail")
				.comment("Propagate iron armor values to chainmail armor as they are close enough that their difficulties balance out.")
				.conversion(Items.CHAINMAIL_HELMET).ingredient(Items.IRON_HELMET).end()
				.conversion(Items.CHAINMAIL_CHESTPLATE).ingredient(Items.IRON_CHESTPLATE).end()
				.conversion(Items.CHAINMAIL_LEGGINGS).ingredient(Items.IRON_LEGGINGS).end()
				.conversion(Items.CHAINMAIL_BOOTS).ingredient(Items.IRON_BOOTS).end()
				.end()
				.group("concrete_powder_to_block")
				.comment("Propagate concrete powder values to concrete blocks.")
				.conversion(Items.WHITE_CONCRETE).ingredient(Items.WHITE_CONCRETE_POWDER).end()
				.conversion(Items.ORANGE_CONCRETE).ingredient(Items.ORANGE_CONCRETE_POWDER).end()
				.conversion(Items.MAGENTA_CONCRETE).ingredient(Items.MAGENTA_CONCRETE_POWDER).end()
				.conversion(Items.LIGHT_BLUE_CONCRETE).ingredient(Items.LIGHT_BLUE_CONCRETE_POWDER).end()
				.conversion(Items.YELLOW_CONCRETE).ingredient(Items.YELLOW_CONCRETE_POWDER).end()
				.conversion(Items.LIME_CONCRETE).ingredient(Items.LIME_CONCRETE_POWDER).end()
				.conversion(Items.PINK_CONCRETE).ingredient(Items.PINK_CONCRETE_POWDER).end()
				.conversion(Items.GRAY_CONCRETE).ingredient(Items.GRAY_CONCRETE_POWDER).end()
				.conversion(Items.LIGHT_GRAY_CONCRETE).ingredient(Items.LIGHT_GRAY_CONCRETE_POWDER).end()
				.conversion(Items.CYAN_CONCRETE).ingredient(Items.CYAN_CONCRETE_POWDER).end()
				.conversion(Items.PURPLE_CONCRETE).ingredient(Items.PURPLE_CONCRETE_POWDER).end()
				.conversion(Items.BLUE_CONCRETE).ingredient(Items.BLUE_CONCRETE_POWDER).end()
				.conversion(Items.BROWN_CONCRETE).ingredient(Items.BROWN_CONCRETE_POWDER).end()
				.conversion(Items.GREEN_CONCRETE).ingredient(Items.GREEN_CONCRETE_POWDER).end()
				.conversion(Items.RED_CONCRETE).ingredient(Items.RED_CONCRETE_POWDER).end()
				.conversion(Items.BLACK_CONCRETE).ingredient(Items.BLACK_CONCRETE_POWDER).end()
				.end()
				.group("damaged_anvil")
				.comment("Calculates values for chipped and damaged anvils based on the average of surviving for 25 uses.")
				//Rough values based on how we factor damage into item EMC based on an average of ~8.3 uses before
				// it degrades a tier, we use 9 so the numbers are slightly worse for how efficiently it translates down
				.conversion(Items.CHIPPED_ANVIL, 25).ingredient(Items.ANVIL, 16).end()
				.conversion(Items.DAMAGED_ANVIL, 25).ingredient(Items.ANVIL, 7).end()
				.end()
				.group("fluid")
				.comment("Calculates the costs of filled buckets and some fluids.")
				.conversionFluid(FluidTags.LAVA, FluidType.BUCKET_VOLUME).ingredient(Items.OBSIDIAN).end()
				.conversionFluid(Tags.Fluids.MILK, FluidType.BUCKET_VOLUME).ingredient(singleEMC, 16).end()//One bucket worth of milk is 16 emc
				.conversion(Items.WATER_BUCKET).ingredient(Items.BUCKET).ingredientFluid(FluidTags.WATER, FluidType.BUCKET_VOLUME).end()
				.conversion(Items.LAVA_BUCKET).ingredient(Items.BUCKET).ingredientFluid(FluidTags.LAVA, FluidType.BUCKET_VOLUME).end()
				.conversion(Items.MILK_BUCKET).ingredient(Items.BUCKET).ingredientFluid(Tags.Fluids.MILK, FluidType.BUCKET_VOLUME).end()
				.end()
				.before(singleEMC, 1)
				.beforeFluid(FluidTags.WATER)
				.before(Items.COBBLESTONE, 64)
				.before(Items.GRANITE, 1_024)
				.before(Items.DIORITE, 1_024)
				.before(Items.ANDESITE, 1_024)
				.before(Items.POINTED_DRIPSTONE, 1_024)
				.before(Items.END_STONE, 64)
				.before(Items.NETHERRACK, 64)
				.before(Items.BASALT, 256)
				.before(Items.BLACKSTONE, 256)
				.before(Items.COBBLED_DEEPSLATE, 128)
				.before(Items.TUFF, 256)
				.before(Items.CALCITE, 2_048)
				.before(Items.DIRT, 64)
				.before(Items.SAND, 64)
				.before(Items.RED_SAND, 64)
				.before(Items.SNOW, 64)
				.before(Items.ICE, 64)
				.before(Items.DEAD_BUSH, 64)
				.before(Items.GRAVEL, 256)
				.before(Items.CACTUS, 512)
				.before(Items.VINE, 512)
				.before(Items.MOSS_BLOCK, 768)
				.before(Items.COBWEB, 768)
				.before(Items.PINK_PETALS, 256)
				.before(Items.LILY_PAD, 1_024)
				.before(Items.SMALL_DRIPLEAF, 1_536)
				.before(Items.BIG_DRIPLEAF, 2_048)
				.before(ItemTags.SMALL_FLOWERS, 1_024)
				.before(ItemTags.TALL_FLOWERS, 2_048)
				.before(Items.RED_MUSHROOM, 2_048)
				.before(Items.BROWN_MUSHROOM, 2_048)
				.before(Items.SUGAR_CANE, 2_048)
				.before(Items.BAMBOO, 2_048)
				.before(Items.SOUL_SAND, 3_136)
				.before(Items.OBSIDIAN, 4_096)
				.before(Items.CRYING_OBSIDIAN, 49_152)
				.before(Items.SPONGE, 8_192)
				.before(Items.SHORT_GRASS, 64)
				.before(Items.SEAGRASS, 64)
				.before(Items.KELP, 64)
				.before(Items.SEA_PICKLE, 1_024)
				.before(Items.TALL_GRASS, 64)
				.before(Items.FERN, 64)
				.before(Items.LARGE_FERN, 64)
				.before(Items.MAGMA_BLOCK, 8_192)
				.before(Items.NETHER_SPROUTS, 64)
				.before(Items.CRIMSON_ROOTS, 64)
				.before(Items.WARPED_ROOTS, 64)
				.before(Items.WEEPING_VINES, 512)
				.before(Items.TWISTING_VINES, 512)
				.before(Items.GLOW_LICHEN, 512)
				.before(Items.CRIMSON_FUNGUS, 2_048)
				.before(Items.WARPED_FUNGUS, 2_048)
				.before(Items.SPORE_BLOSSOM, 4_096)
				.before(Items.TUBE_CORAL_BLOCK, 4_096)
				.before(Items.BRAIN_CORAL_BLOCK, 4_096)
				.before(Items.BUBBLE_CORAL_BLOCK, 4_096)
				.before(Items.FIRE_CORAL_BLOCK, 4_096)
				.before(Items.HORN_CORAL_BLOCK, 4_096)
				.before(Items.DEAD_TUBE_CORAL_BLOCK, 256)
				.before(Items.DEAD_BRAIN_CORAL_BLOCK, 256)
				.before(Items.DEAD_BUBBLE_CORAL_BLOCK, 256)
				.before(Items.DEAD_FIRE_CORAL_BLOCK, 256)
				.before(Items.DEAD_HORN_CORAL_BLOCK, 256)
				.before(Items.TUBE_CORAL_FAN, 1_024)
				.before(Items.BRAIN_CORAL_FAN, 1_024)
				.before(Items.BUBBLE_CORAL_FAN, 1_024)
				.before(Items.FIRE_CORAL_FAN, 1_024)
				.before(Items.HORN_CORAL_FAN, 1_024)
				.before(Items.DEAD_TUBE_CORAL_FAN, 64)
				.before(Items.DEAD_BRAIN_CORAL_FAN, 64)
				.before(Items.DEAD_BUBBLE_CORAL_FAN, 64)
				.before(Items.DEAD_FIRE_CORAL_FAN, 64)
				.before(Items.DEAD_HORN_CORAL_FAN, 64)
				.before(Items.TUBE_CORAL, 1_024)
				.before(Items.BRAIN_CORAL, 1_024)
				.before(Items.BUBBLE_CORAL, 1_024)
				.before(Items.FIRE_CORAL, 1_024)
				.before(Items.HORN_CORAL, 1_024)
				.before(Items.DEAD_TUBE_CORAL, 64)
				.before(Items.DEAD_BRAIN_CORAL, 64)
				.before(Items.DEAD_BUBBLE_CORAL, 64)
				.before(Items.DEAD_FIRE_CORAL, 64)
				.before(Items.DEAD_HORN_CORAL, 64)
				.before(Items.CHORUS_PLANT, 4_096)
				.before(Items.CHORUS_FLOWER, 6_144)
				.before(Items.CHORUS_FRUIT, 12_288)
				.before(Items.SCULK_VEIN, 256)
				.before(Items.SCULK_CATALYST, 514_560)
				.before(Tags.Items.SEEDS_WHEAT, 1_024)
				.before(Tags.Items.SEEDS_BEETROOT, 1_024)
				.before(Items.MELON_SLICE, 1_024)
				.before(Items.SWEET_BERRIES, 1_024)
				.before(Items.GLOW_BERRIES, 1_024)
				.before(Tags.Items.CROPS_WHEAT, 1_536)
				.before(Tags.Items.CROPS_NETHER_WART, 1_536)
				.before(Items.APPLE, 8_192)
				.before(Tags.Items.PUMPKINS_NORMAL, 9_216)
				.before(Items.HONEY_BOTTLE, 3_072)
				.before(Items.PORKCHOP, 4_096)
				.before(Items.BEEF, 4_096)
				.before(Items.CHICKEN, 4_096)
				.before(Items.RABBIT, 4_096)
				.before(Items.MUTTON, 4_096)
				.before(Items.COD, 4_096)
				.before(Items.SALMON, 4_096)
				.before(Items.TROPICAL_FISH, 4_096)
				.before(Items.PUFFERFISH, 4_096)
				.before(Tags.Items.CROPS_CARROT, 4_096)
				.before(Tags.Items.CROPS_BEETROOT, 4_096)
				.before(Tags.Items.CROPS_POTATO, 4_096)
				.before(Items.POISONOUS_POTATO, 4_096)
				.before(Items.STRING, 768)
				.before(Items.ROTTEN_FLESH, 2_048)
				.before(Items.SLIME_BALL, 2_048)
				.before(Items.EGG, 2_048)
				.before(Items.TURTLE_SCUTE, 6_144)
				.before(Items.TURTLE_EGG, 12_288)
				//Regular horns
				.before(horn(registries, Instruments.PONDER_GOAT_HORN), 6_144)
				.before(horn(registries, Instruments.SING_GOAT_HORN), 6_144)
				.before(horn(registries, Instruments.SEEK_GOAT_HORN), 6_144)
				.before(horn(registries, Instruments.FEEL_GOAT_HORN), 6_144)
				//Screaming horns
				.before(horn(registries, Instruments.ADMIRE_GOAT_HORN), 12_288)
				.before(horn(registries, Instruments.CALL_GOAT_HORN), 12_288)
				.before(horn(registries, Instruments.YEARN_GOAT_HORN), 12_288)
				.before(horn(registries, Instruments.DREAM_GOAT_HORN), 12_288)
				.before(Items.FEATHER, 3_072)
				.before(Items.RABBIT_HIDE, 1_024)
				.before(Items.RABBIT_FOOT, 8_192)
				.before(Items.SPIDER_EYE, 8_192)
				.before(Items.PHANTOM_MEMBRANE, 12_288)
				.before(Items.GUNPOWDER, 12_288)
				.before(Items.SKELETON_SKULL, 16_384)
				.before(Items.ZOMBIE_HEAD, 16_384)
				.before(Items.CREEPER_HEAD, 16_384)
				.before(Items.PIGLIN_HEAD, 16_384)
				.before(Items.PIGLIN_BANNER_PATTERN, 32_768)
				.before(Items.FLOW_BANNER_PATTERN, 1_310_720)
				.before(Items.GUSTER_BANNER_PATTERN, 782_336)
				.before(Items.ENDER_PEARL, 65_536)
				.before(Items.NAUTILUS_SHELL, 65_536)
				.before(Tags.Items.RODS_BLAZE, 98_304)
				.before(Tags.Items.RODS_BREEZE, 147_456)
				.before(Items.SHULKER_SHELL, 131_072)
				.before(Items.SNIFFER_EGG, 131_072)
				.before(Items.GHAST_TEAR, 262_144)
				.before(Items.TRIDENT, 1_049_472)
				.before(Items.HEART_OF_THE_SEA, 2_097_152)
				.before(Items.HEAVY_CORE, 2_621_440)
				.before(Items.DRAGON_EGG, 16_777_216)
				.before(Items.SADDLE, 12_288)
				.before(Items.ECHO_SHARD, 12_288)
				.before(Items.NAME_TAG, 12_288)
				.before(ItemTags.CREEPER_DROP_MUSIC_DISCS, 131_072)
				.before(Items.DISC_FRAGMENT_5, 12_288)
				.before(Items.MUSIC_DISC_CREATOR, 2_621_440)
				.before(Items.MUSIC_DISC_CREATOR_MUSIC_BOX, 524_288)
				.before(Items.MUSIC_DISC_OTHERSIDE, 393_216)
				.before(Items.MUSIC_DISC_PIGSTEP, 524_288)
				.before(Items.MUSIC_DISC_PRECIPICE, 782_336)
				.before(Items.MUSIC_DISC_RELIC, 651_264)
				.before(Items.FLINT, 256)
				.before(Items.COAL, 8_192)
				.before(Tags.Items.GEMS_QUARTZ, 16_384)
				.before(Items.PRISMARINE_SHARD, 16_384)
				.before(Items.PRISMARINE_CRYSTALS, 32_768)
				.before(Items.INK_SAC, 1_024)
				.before(Items.COCOA_BEANS, 4_096)
				.before(Items.LAPIS_LAZULI, 55_296)
				.before(Tags.Items.GEMS_EMERALD, 1_048_576)
				.before(Tags.Items.NETHER_STARS, 8_912_896)
				.before(Items.CLAY_BALL, 1_024)
				.before(ItemTags.DECORATED_POT_SHERDS, 13_824)
				.before(Items.BONE, 9_216)
				.before(Items.SNOWBALL, 64)
				.before(Items.FILLED_MAP, 94_208)
				.before(ItemTags.LOGS, 2_048)
				.before(ItemTags.PLANKS, 512)
				.before(ItemTags.SAPLINGS, 2_048)
				.before(Tags.Items.RODS_WOODEN, 256)
				.before(ItemTags.LEAVES, 64)
				.before(Items.MANGROVE_ROOTS, 256)
				.before(ItemTags.WOOL, 3_072)
				.before(Items.ARMADILLO_SCUTE, 3_072)
				.before(Items.NETHERITE_SCRAP, 786_432)
				.before(Tags.Items.GEMS_DIAMOND, 524_288)
				.before(Tags.Items.DUSTS_REDSTONE, 4_096)
				.before(Tags.Items.DUSTS_GLOWSTONE, 24_576)
				//Smithing Trims: Based on fractional amounts of the duplication recipe cost and how rare the trim is in the world to begin with:
				// https://docs.google.com/spreadsheets/d/1DYax3nrIAeEizyby2HpCJsrUbGum-bGSG3AVF2NJk5A/edit?pli=64#gid=0
				.before(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE, 479_808)
				//Armor trim templates
				.before(Items.EYE_ARMOR_TRIM_SMITHING_TEMPLATE, 1_473_088)
				.before(Items.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE, 3_670_080)
				.before(Items.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE, 3_449_472)
				.before(Items.VEX_ARMOR_TRIM_SMITHING_TEMPLATE, 3_322_688)
				.before(Items.WILD_ARMOR_TRIM_SMITHING_TEMPLATE, 2_729_024)
				.before(Items.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE, 2_525_760)
				.before(Items.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE, 1_415_424)
				.before(Items.WARD_ARMOR_TRIM_SMITHING_TEMPLATE, 1_259_328)
				.before(Items.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE, 1_189_632)
				.before(Items.COAST_ARMOR_TRIM_SMITHING_TEMPLATE, 785_344)
				.before(Items.RIB_ARMOR_TRIM_SMITHING_TEMPLATE, 659_840)
				.before(Items.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE, 651_264)
				.before(Items.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE, 651_264)
				.before(Items.HOST_ARMOR_TRIM_SMITHING_TEMPLATE, 651_264)
				.before(Items.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE, 651_264)
				.before(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, 482_112)
				//TODO: Figure out how we actually calculated the above ones in terms of an equation
				.before(Items.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE, 1_953_792)
				.before(Items.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE, 651_264)
				;
	}

	private ItemStack horn(HolderLookup.Provider registries, ResourceKey<Instrument> instrument) {
		return InstrumentItem.create(Items.GOAT_HORN, registries.holderOrThrow(instrument));
	}

	private static NormalizedSimpleStack ingotTag(String ingot) {
		return NSSItem.createTag(Tags.Items.INGOTS.location().withSuffix("/" + ingot));
	}

	private static NormalizedSimpleStack gemTag(String gem) {
		return NSSItem.createTag(Tags.Items.GEMS.location().withSuffix("/" + gem));
	}
}
